Session endpoints
spritzle/spritzle pull request #6
Opened 2018-04-26 22:28 UTC by gazpachoking

Renames some stuff to not confuse session 'stats' with 'status'.
Adds some endpoints to get/modify session settings.

2018-04-27 02:45 UTC, aresch requested changes
These are already implemented in /settings: https://github.com/spritzle/spritzle/blob/master/spritzle/resource/settings.py

Do you think it should be moved to /session/settings?

2018-04-27 02:51 UTC, gazpachoking commented
Oh. Hmm, not sure how I missed that. Not sure now whether it should be moved.

2018-04-27 02:51 UTC, gazpachoking commented
I think the old GET on /session giving the debug stats is a bit useless though.

2018-04-27 02:59 UTC, aresch commented
I suppose we could move it to /session/stats .. I'm not really sure what we could return in /session though, maybe the output of session.save_state()?

2018-04-27 03:11 UTC, gazpachoking commented
Well if the session settings stay in /settings, I thing the whole /session endpoint could go away? Are those stats that useful to a client?

Only slightly related to this discussion: If you change the session settings now, that won't be persisted through restarts, will it? Should it?

2018-04-27 04:13 UTC, aresch commented
It should be persisted through session.save_state() which we write to disk and load on startup. I think keeping around the session stats could be useful, why remove it?

2018-04-27 04:23 UTC, gazpachoking commented
Ahh, yeah, I think it may be some windows bullcrap that prevents the session save_state from calling for me (until there is a method to quit other than KeyboardInterrupt, which is not working on windows.) I don't really see a reason to remove the session stats, I just didn't have a strong desire to keep it. I'm fine with it staying in, doesn't harm anything.

2018-04-27 15:39 UTC, gazpachoking commented
I'm thinking moving the settings up under /session makes sense, no idea what /session should return though.

2018-04-27 21:40 UTC, aresch commented on spritzle/resource/session.py
> +@routes.put('/settings')
@routes.put('/session/settings')

2018-04-29 21:17 UTC, aresch reviewed
The example for GET /session needs to be updated too.

2018-04-30 13:22 UTC, gazpachoking commented
Ahh, good catch. Done.

2018-04-30 17:44 UTC, aresch commented
I'll merge this PR, but you could please make a PR for spritzle-cli for the new endpoints?

2018-04-30 17:44 UTC, aresch approved these changes

2018-04-30 17:45 UTC, merged

2018-04-30 18:42 UTC, gazpachoking commented
Yep, can do.